version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    tty: true
    stdin_open: true
    ports:
      - "80:80"
    depends_on:
      - mongo