version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: twitter

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    tty: true
    stdin_open: true
    ports:
      - "80:80"
    depends_on:
      - mysql